import { useEffect, useState } from 'react';
type Metrics = { total: number; overdue: number; today: number; upcoming: number; noDeadline: number; invalidDeadline: number; maxOverdueDays: number };
type Issue = { key: string; summary: string; dueDate: string | null; status: string; priority: string; bucket: string; daysOverdue: number; url: string | null };
type Connection = { connected: boolean; info: { name: string } | null; tools: { name: string; description: string; inputSchema: unknown }[]; events: { time: string; method: string; detail: string }[] };
type State = { day: number; title: string; source: string; busy: boolean; connection: Connection; requests: Record<string,string>; last: { result: { source: string; date: string; metrics: Metrics; issues: Issue[] }; modelMetrics: Metrics; answer: string; agentMode: string } | null; budget: { estimatedUsd: number; requests: number; reservedUsd: number }; hasTracker: boolean; hasOpenAI: boolean };
const labels: Record<string,string> = { overdue: 'Просрочено', today: 'Сегодня', upcoming: 'Позже', noDeadline: 'Без срока', invalidDeadline: 'Неверная дата' };
export function App() {
  const [state, setState] = useState<State | null>(null), [busy, setBusy] = useState(false), [error, setError] = useState('');
  const [request, setRequest] = useState('all'), [mode, setMode] = useState('demo');
  async function refresh() { const response = await fetch('/api/state'); if (!response.ok) throw new Error('Сайт недоступен.'); setState(await response.json()); }
  useEffect(() => { refresh().catch(e => setError(e.message)); }, []);
  async function act(action: string, body: Record<string,unknown> = {}) {
    setBusy(true); setError('');
    try { const response = await fetch(`/api/${action}`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(body) }); const data = await response.json(); if (!response.ok) throw new Error(data.error); setState(data); }
    catch(e) { setError((e as Error).message); await refresh().catch(() => {}); } finally { setBusy(false); }
  }
  const connection = state?.connection, result = state?.last?.result, metrics = result?.metrics;
  return <div className="shell"><aside><a className="brand" href="/">Т<span>·</span>ЛАБ</a><div className="series">MCP / ЯНДЕКС ТРЕКЕР</div><nav>{[16,17,18,19,20].map((day,i) => <div className={day === 17 ? 'nav-item active' : 'nav-item'} key={day}><span>{day}</span>{['Подключение','Первый инструмент','Расписание','Цепочка','Оркестрация'][i]}</div>)}</nav><div className="aside-note">Только назначенные мне задачи<br/>Часовой пояс: Екатеринбург</div></aside>
  <main><header><span className="eyebrow">ДЕНЬ 17 / ВЫЗОВ ИНСТРУМЕНТА</span><span className="local"><i/> Локальное приложение</span></header>
  <section className="hero"><div><h1>Задачи становятся<br/>доступны агенту</h1><p>Агент вызывает поиск через MCP. Таблица остаётся на компьютере, модель получает только показатели.</p></div><div className="hero-number">17<span>/20</span></div></section>
  <section className="panel controls"><label>Источник задач<select aria-label="Источник задач" disabled={busy} value={state?.source ?? 'demo'} onChange={e => act('source', {source: e.target.value})}><option value="demo">Учебные данные</option><option value="live">Мой Яндекс Трекер</option></select></label><div><span className={'badge ' + (connection?.connected ? 'good' : '')}>{connection?.connected ? 'MCP подключён' : 'MCP не подключён'}</span><p className="muted">{connection?.info?.name ?? 'tracker-tools'} · {connection?.tools.length ?? 0} инструментов</p></div><button className="secondary" disabled={busy} onClick={() => act(connection?.connected ? 'disconnect' : 'connect')}>{connection?.connected ? 'Отключить' : 'Подключить MCP'}</button></section>
  <section className="panel request-panel"><label>Запрос агенту<select aria-label="Запрос агенту" disabled={busy} value={request} onChange={e => setRequest(e.target.value)}>{Object.entries(state?.requests ?? {all:'Покажи общую сводку моих незавершённых задач.'}).map(([key,label]) => <option key={key} value={key}>{label}</option>)}</select></label><label>Исполнение<select aria-label="Исполнение" disabled={busy} value={mode} onChange={e => setMode(e.target.value)}><option value="demo">Демонстрация без модели</option><option value="live">Настоящий агент · OpenAI</option></select></label><button disabled={busy || (mode === 'live' && !state?.hasOpenAI)} onClick={() => act('run', {request,mode})}>{busy ? 'Выполняется…' : 'Выполнить запрос →'}</button><p className="muted wide">Источник задач и режим агента независимы. Демонстрация использует настоящий MCP, а выбор инструмента выполняет код. Запросы заданы шаблонами, чтобы личный текст не отправлялся модели.</p></section>
  {error && <p className="error" role="alert">{error}</p>}
  <div className="metrics">{[['Найдено', metrics?.total],['Просрочено',metrics?.overdue],['Срок сегодня',metrics?.today],['Без дедлайна',metrics?.noDeadline]].map(([label,value],i) => <section className={'metric metric-'+i} key={label}><span>{label}</span><strong>{value ?? '—'}</strong></section>)}</div>
  <section className="panel"><div className="section-title"><h2>Мои задачи</h2><span className="badge">{result ? `${result.source === 'live' ? 'Трекер' : 'Учебный пример'} · ${result.date}` : 'Запрос ещё не выполнен'}</span></div><p className="muted">Полные строки доступны только локальному приложению.</p>{!result ? <div className="empty">Выберите запрос и запустите поиск.</div> : !result.issues.length ? <div className="empty">Задач для выбранного периода нет.</div> : <div className="table-wrap"><table><thead><tr><th>Задача</th><th>Дедлайн</th><th>Срок</th><th>Статус</th></tr></thead><tbody>{result.issues.map(issue => <tr key={issue.key}><td>{issue.url ? <a href={issue.url} target="_blank" rel="noreferrer">{issue.key} ↗</a> : <span className="issue-key">{issue.key}</span>}<strong>{issue.summary}</strong></td><td>{issue.dueDate ?? 'Не задан'}</td><td><span className={'badge '+ (issue.bucket === 'overdue' ? 'bad' : 'good')}>{labels[issue.bucket]}{issue.daysOverdue ? ` · ${issue.daysOverdue} дн.` : ''}</span></td><td>{issue.status}</td></tr>)}</tbody></table></div>}</section>
  <div className="columns lower"><section className="panel"><h2>{state?.last?.agentMode === 'live' ? 'Ответ агента' : 'Результат выполнения'}</h2><p className="answer">{state?.last?.answer ?? 'Здесь появится объяснение полученных показателей.'}</p><details><summary>Что доступно языковой модели</summary><pre>{JSON.stringify(state?.last?.modelMetrics ?? {}, null, 2)}</pre><p className="muted">Только числовые поля. Тексты, ключи и ссылки задач не передаются.</p></details><p className="muted">Запросов к OpenAI: {state?.budget.requests ?? 0} · оценка расхода: ${(state?.budget.estimatedUsd ?? 0).toFixed(5)}</p></section>
  <section className="panel"><h2>Путь вызова MCP</h2><ol className="timeline">{connection?.events.map((event,i) => <li key={i}><small>{new Date(event.time).toLocaleTimeString('ru-RU')}</small><strong>{event.method}</strong><p>{event.detail}</p></li>)}</ol>{!connection?.events.length && <p className="muted">Приложение → MCP → Трекер → числовые показатели → ответ.</p>}<details><summary>Каталог и параметры инструментов</summary><pre>{JSON.stringify(connection?.tools ?? [], null, 2)}</pre></details></section></div>
  <footer>Данные Трекера читаются от вашего имени. Приложение сохраняет локальный результат вне репозитория.<br/>Учебные данные вымышлены; результаты настоящего API отмечаются отдельно.</footer></main></div>;
}
