import {useEffect,useState} from 'react';
type Schedule={source:string;enabled:boolean;time:string};
type Issue={label:string;dueDate:string|null;bucket:string;daysOverdue:number};
type Digest={schedule:Schedule;nextRun:string|null;running:boolean;latest:null|{date:string;finished:string;source:string;metrics:Record<string,number>;issues:Issue[]};history:{id:string;status:string;trigger:string;started:string;attempts:number;error:string|null}[]};
type State={digest:Digest;connection:{connected:boolean;tools:{name:string;description:string;inputSchema:unknown}[]}};
export function App(){
 const[state,setState]=useState<State|null>(null),[source,setSource]=useState('demo'),[time,setTime]=useState('09:00'),[enabled,setEnabled]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState('');
 async function refresh(initial=false){const response=await fetch('/api/state');const data=await response.json();if(!response.ok)throw new Error(data.error);setState(data);if(initial){setSource(data.digest.schedule.source);setTime(data.digest.schedule.time);setEnabled(data.digest.schedule.enabled);}}
 useEffect(()=>{refresh(true).catch(e=>setError(e.message));const timer=setInterval(()=>refresh().catch(e=>setError(e.message)),5000);return()=>clearInterval(timer);},[]);
 async function act(path:string,body:unknown={}){setBusy(true);setError('');try{const response=await fetch('/api/'+path,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const data=await response.json();if(!response.ok)throw new Error(data.error);setState(data);}catch(e){setError((e as Error).message);await refresh().catch(()=>{});}finally{setBusy(false);}}
 const digest=state?.digest,latest=digest?.latest;
 return <div className="shell"><aside><a className="brand" href="/">Т<span>·</span>ЛАБ</a><div className="series">MCP / ЯНДЕКС ТРЕКЕР</div><nav>{[16,17,18,19,20].map((day,i)=><div className={day===18?'nav-item active':'nav-item'} key={day}><span>{day}</span>{['Подключение','Первый инструмент','Расписание','Цепочка','Оркестрация'][i]}</div>)}</nav><div className="aside-note">Фоновый исполнитель<br/>SQLite · локальное хранение</div></aside><main><header><span className="eyebrow">ДЕНЬ 18 / ФОНОВЫЕ ЗАДАЧИ</span><span className="local"><i/> {state?.connection.connected?'MCP подключён':'Подключение…'}</span></header><section className="hero"><div><h1>Утро начинается<br/>с ясной картины</h1><p>Просроченные задачи и сроки на сегодня — в одной сводке. Расписание продолжает работать при закрытой вкладке.</p></div><div className="hero-number">18<span>/20</span></div></section>
 <section className="panel"><div className="section-title"><h2>Утренняя сводка</h2><span className={'badge '+(digest?.schedule.enabled?'good':'')}>{digest?.schedule.enabled?'Расписание включено':'Расписание выключено'}</span></div><div className="schedule-controls"><label>Источник задач<select aria-label="Источник задач" disabled={busy} value={source} onChange={e=>setSource(e.target.value)}><option value="demo">Учебные данные</option><option value="live">Мой Яндекс Трекер</option></select></label><label>Время · Екатеринбург<input aria-label="Время сводки" type="time" value={time} onChange={e=>setTime(e.target.value)}/></label><label className="check-label"><input type="checkbox" checked={enabled} onChange={e=>setEnabled(e.target.checked)}/> По будням</label><button disabled={busy} onClick={()=>act('schedule',{source,time,enabled})}>Сохранить расписание</button></div><div className="schedule-bottom"><p>Следующий запуск: <strong>{digest?.nextRun??'после включения расписания'}</strong><br/><span className="muted">Ручной запуск приложения обязателен. Выключенный или спящий компьютер не выполняет расписание.</span></p><button className="secondary" disabled={busy||digest?.running} onClick={()=>act('run')}>{busy||digest?.running?'Формируется…':'Обновить сводку сейчас'}</button></div><p className="muted">Кнопка использует сохранённый источник, обновляет отчёт и сохраняет расписание без изменений. Модель не вызывается.</p></section>
 {error&&<p role="alert" className="error">{error}</p>}<div className="metrics">{[['Незавершённых',latest?.metrics.total],['Просрочено',latest?.metrics.overdue],['Срок сегодня',latest?.metrics.today],['Без дедлайна',latest?.metrics.noDeadline]].map(([label,value],i)=><section className={'metric metric-'+i} key={label}><span>{label}</span><strong>{value??'—'}</strong></section>)}</div>
 <section className="panel"><div className="section-title"><h2>Задачи, которым нужно внимание</h2><span className="badge">{latest?`${latest.source==='live'?'Трекер':'Учебный пример'} · ${latest.date}`:'Сводка ещё не создана'}</span></div>{latest&&<p className="muted">Названия, ключи и ссылки скрыты; номера относятся к этому снимку. Снимок: {new Date(latest.finished).toLocaleString('ru-RU')}. Автоматическое обновление страницы — каждые 5 секунд.</p>}{!latest?<div className="empty">Сохраните настройки и обновите сводку.</div>:<div className="table-wrap"><table><thead><tr><th>Задача</th><th>Дедлайн</th><th>Категория</th></tr></thead><tbody>{latest.issues.filter(i=>['overdue','today','noDeadline','invalidDeadline'].includes(i.bucket)).map(issue=><tr key={issue.label}><td><strong>{issue.label}</strong></td><td>{issue.dueDate??'Не задан'}</td><td><span className={'badge '+(issue.bucket==='overdue'?'bad':'good')}>{issue.bucket==='overdue'?`Просрочено · ${issue.daysOverdue} дн.`:issue.bucket==='today'?'Сегодня':issue.bucket==='noDeadline'?'Без дедлайна':'Неверная дата'}</span></td></tr>)}</tbody></table>{!latest.issues.length&&<p className="empty">Незавершённых задач нет.</p>}</div>}</section>
 <div className="columns lower"><section className="panel"><h2>История запусков</h2>{!digest?.history.length&&<p className="muted">Запусков ещё нет.</p>}<ol className="timeline">{digest?.history.map(run=><li key={run.id}><strong>{run.status==='completed'?'Сводка сохранена':run.status==='running'?'Выполняется':'Ошибка'}</strong><p>{new Date(run.started).toLocaleString('ru-RU')} · {run.trigger==='scheduled'?'По расписанию':'Вручную'} · попытка {run.attempts}</p>{run.error&&<p>{run.error}</p>}</li>)}</ol></section><section className="panel"><h2>Как это работает</h2><p className="answer">MCP-инструмент сохраняет расписание в SQLite. Фоновый исполнитель проверяет время, читает задачи и записывает результат. После перезапуска расписание и история восстанавливаются.</p><p className="muted">Один утренний запуск на дату и источник. После сбоя — до трёх попыток. Пропущенный запуск выполняется при старте после установленного времени в будний день.</p><details><summary>Три MCP-инструмента</summary><pre>{JSON.stringify(state?.connection.tools??[],null,2)}</pre></details></section></div><footer>Рабочие данные хранятся вне репозитория. Изменения в Яндекс Трекере не выполняются.<br/>Закрытие приложения останавливает фоновые задачи; история остаётся на диске.</footer></main></div>;
}
