import { useEffect, useState, type ReactNode } from 'react';
export type Chunk = {source:string;title:string;section:string;chunk_id:string;text:string;start:number;end:number;score?:number;strategy:string};
export type Question = {id:string;question:string;expected:string;sources:string[]};
export type State = {day:number;title:string;description:string;words:number;hasKey:boolean;busy:boolean;budget:{spent:number;reserved:number;limit:number;calls:number};indexes:{strategy:string;ready:boolean;count:number}[];documents:{source:string;title:string;words:number}[];questions:Question[];report:any;[key:string]:any};
export async function api(path:string, body?:unknown) { const r=await fetch('/api/'+path, body===undefined?undefined:{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const data=await r.json();if(!r.ok)throw new Error(data.error??'Ошибка запроса');return data; }
export function Chunks({items}:{items:Chunk[]}) { return <div className="chunks">{items.map(c=><details key={c.chunk_id}><summary><span className="score">{c.score===undefined?'¶':c.score.toFixed(3)}</span><span>{c.title}<small>{c.section}</small></span></summary><div className="chunk-content"><code>{c.chunk_id}</code><p className="muted">{c.source} · символы {c.start}–{c.end}</p><pre>{c.text}</pre></div></details>)}</div>; }
export function Report({report}:{report:any}) { if(!report)return <p className="muted">Сохранённый эксперимент пока не выполнен.</p>;return <><div className="notice">Реальный сохранённый эксперимент · {report.date} · просмотр без вызовов API</div>{report.summary&&<div className="report-summary">{Object.entries(report.summary).map(([k,v])=><div key={k}><small>{k}</small><strong>{String(v)}</strong></div>)}</div>}{report.rows?.map((row:any,i:number)=><details key={i} className="report-row"><summary>{row.question??row.strategy??row.name??`Проверка ${i+1}`}{row.mode&&<span className="pill">{row.mode}</span>}</summary>{row.text&&<><p className="muted">Ожидание: {row.expected}</p><div className="answer">{row.text}</div>{row.review&&<div className="notice">Разбор: {row.review.note} · {row.review.score}/2</div>}{row.context?.length>0&&<details><summary>Найденные фрагменты</summary><Chunks items={row.context}/></details>}</>}<details><summary>Полный протокол</summary><pre>{JSON.stringify(row,null,2)}</pre></details></details>)}<a className="button secondary" download="experiment.json" href={'data:application/json;charset=utf-8,'+encodeURIComponent(JSON.stringify(report,null,2))}>Скачать протокол JSON</a></>; }
export default function App({extra}:{extra?:(state:State,run:(work:()=>Promise<any>)=>Promise<void>)=>ReactNode}) {
  const [state,setState]=useState<State|null>(null),[tab,setTab]=useState('lab'),[strategy,setStrategy]=useState('structure'),[chunks,setChunks]=useState<Chunk[]>([]),[query,setQuery]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false),[source,setSource]=useState('');
  const refresh=async()=>setState(await api('state'));
  useEffect(()=>{refresh().catch(e=>setError(e.message));},[]);
  async function run(work:()=>Promise<any>) {setBusy(true);setError('');try{await work();await refresh();}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
  if(!state)return <main><p>{error||'Открываем лабораторию…'}</p></main>;
  const visible=source?chunks.filter(c=>c.source===source):chunks;
  return <><header><a className="brand" href="/">◈ <span>AI TUTORS <b>/ RAG LAB</b></span></a><span className="local">● Локальная лаборатория</span></header><main><div className="eyebrow">ПРАКТИКУМ / ДЕНЬ {state.day} / 21 → 25</div><div className="hero"><div><h1>{state.title}</h1><p>{state.description}</p></div><span className="day-number">{state.day}</span></div><div className="metrics"><div><strong>{state.documents.length}</strong><span>документов в базе</span></div><div><strong>{state.words.toLocaleString('ru')}</strong><span>слов · {(state.words/500).toFixed(1)} условных страниц</span></div><div><strong>{state.indexes.reduce((s,x)=>s+x.count,0)}</strong><span>фрагментов · две стратегии</span></div><div><strong>${state.budget.spent.toFixed(4)} <small>/ $1</small></strong><span>расход серии · резерв ${state.budget.reserved.toFixed(4)}</span></div></div><nav><button className={tab==='lab'?'active':''} onClick={()=>setTab('lab')}>Лаборатория</button><button className={tab==='corpus'?'active':''} onClick={()=>setTab('corpus')}>Документы и вопросы</button><button className={tab==='report'?'active':''} onClick={()=>setTab('report')}>Результаты эксперимента</button></nav>{error&&<div role="alert" className="error">{error}</div>}{busy&&<div role="status" className="notice">Выполняется запрос. Результат появится после ответа сервера…</div>}
  {tab==='lab'&&<fieldset disabled={busy}><>{extra?.(state,run)}{!extra&&<div className="workspace"><section className="panel controls"><div className="eyebrow">01 / ПОСТРОЕНИЕ ИНДЕКСА</div><h2>Где провести границы?</h2><p className="muted">Один корпус, два способа деления. Выберите стратегию и посмотрите, какие фрагменты получит поиск.</p><label>Стратегия<select value={strategy} onChange={e=>{setStrategy(e.target.value);setChunks([]);}}><option value="structure">По заголовкам и разделам</option><option value="fixed">Фиксированный размер</option></select></label><div className="settings-note">До 1800 символов · перекрытие 200 символов внутри длинных блоков. Эмбеддинги: 512 чисел.</div><button className="secondary" onClick={()=>run(async()=>setChunks(await api('chunks',{strategy})))}>Показать разбиение</button><button onClick={()=>run(async()=>{await api('build',{strategy});setChunks(await api('chunks',{strategy}));})}>Построить индекс</button><p className="muted">{state.indexes.find(x=>x.strategy===strategy)?.ready?'✓ Индекс сохранён в SQLite':'Индекс ещё не построен'}</p><div className="rule"/><label>Вопрос для поиска<textarea value={query} onChange={e=>setQuery(e.target.value)} placeholder="Например: как продолжить работу после паузы?"/></label><button disabled={!query.trim()} onClick={()=>run(async()=>setChunks(await api('search',{question:query,strategy})))}>Найти фрагменты</button><small>Новые эмбеддинги используют API. Готовое разбиение и сохранённые результаты доступны без ключа.</small></section><section className="panel"><div className="section-heading"><h2>Фрагменты документов</h2><span className="pill">{visible.length}</span></div><select aria-label="Фильтр документов" value={source} onChange={e=>setSource(e.target.value)}><option value="">Все документы</option>{state.documents.map(d=><option key={d.source} value={d.source}>{d.title}</option>)}</select>{visible.length?<Chunks items={visible}/>:<div className="empty"><span>⌕</span><h3>Посмотрите внутрь индекса</h3><p>Покажите разбиение или выполните поиск.<br/>Здесь появятся фрагменты, их границы и источники.</p></div>}</section></div>}</></fieldset>}
  {tab==='corpus'&&<div className="workspace"><section className="panel"><h2>Зафиксированный корпус</h2><p>README дней 1–20. Исходные условия удалены из снимка, чтобы уменьшить повторы. Эквивалент страницы: 500 слов; это мера объёма, а не число листов PDF.</p>{state.documents.map(d=><div className="document" key={d.source}><strong>{d.title}</strong><small>{d.source} · {d.words} слов</small></div>)}</section><section className="panel"><h2>10 контрольных вопросов</h2><p className="muted">Ожидания записаны до эксперимента. Вопросы и эталоны не входят в индекс.</p>{state.questions.map(q=><details key={q.id}><summary>{q.question}</summary><p>{q.expected}</p><small>{q.sources.join(', ')}</small></details>)}</section></div>}
  {tab==='report'&&<section className="panel"><h2>Что получилось на практике</h2><Report report={state.report}/></section>}<footer>Индекс и поиск — на этом компьютере. Новые тексты для эмбеддингов и запросы к модели отправляются в OpenAI. Ключ доступен только серверу.</footer></main></>;
}
