import {useEffect,useState} from 'react';
type Step={name:string;status:string;input?:unknown;output?:unknown;durationMs?:number};
type Run={status:string;steps:Step[];error:string|null;result:{date:string;metrics:Record<string,number>;issues:{label:string;dueDate:string|null;bucket:string}[]}|null;report:{reportId:string;markdownFile:string;jsonFile:string}|null};
type State={source:string;busy:boolean;last:Run|null;dataDirectory:string;connection:{connected:boolean;tools:{name:string;description:string}[]}};
const names:Record<string,string>={search_issues:'Получить задачи',summarize_issues:'Рассчитать сводку',save_report:'Сохранить отчёт'};
const statuses:Record<string,string>={waiting:'Ожидает',running:'Выполняется',completed:'Готово',failed:'Ошибка',skipped:'Пропущен'};
export function App(){
 const[state,setState]=useState<State|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState(''),[preview,setPreview]=useState('');
 async function refresh(){const r=await fetch('/api/state');if(!r.ok)throw new Error('Сайт недоступен.');setState(await r.json());}
 useEffect(()=>{refresh().catch(e=>setError(e.message));const timer=setInterval(()=>refresh().catch(()=>{}),1000);return()=>clearInterval(timer);},[]);
 async function act(path:string,body:unknown={}){setBusy(true);setError('');setPreview('');try{const r=await fetch('/api/'+path,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const data=await r.json();if(!r.ok)throw new Error(data.error);setState(data);}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 async function showReport(){try{const r=await fetch('/api/report/'+state?.last?.report?.reportId);const data=await r.json();if(!r.ok)throw new Error(data.error);setPreview(data.markdown);}catch(e){setError((e as Error).message);}}
 const running=busy||state?.busy,run=state?.last,steps=run?.steps??['search_issues','summarize_issues','save_report'].map(name=>({name,status:'waiting'} as Step));
 return <div className="shell"><aside><a className="brand" href="/">Т<span>·</span>ЛАБ</a><div className="series">MCP / ЯНДЕКС ТРЕКЕР</div><nav>{[16,17,18,19,20].map((day,i)=><div className={day===19?'nav-item active':'nav-item'} key={day}><span>{day}</span>{['Подключение','Первый инструмент','Расписание','Цепочка','Оркестрация'][i]}</div>)}</nav><div className="aside-note">Три инструмента<br/>Один автоматический запуск</div></aside><main><header><span className="eyebrow">ДЕНЬ 19 / КОМПОЗИЦИЯ ИНСТРУМЕНТОВ</span><span className="local"><i/> Локальное приложение</span></header><section className="hero"><div><h1>От задач<br/>к готовому отчёту</h1><p>Один запуск связывает получение данных, расчёт сроков и сохранение результата. Каждый шаг выполняется через MCP.</p></div><div className="hero-number">19<span>/20</span></div></section>
 <section className="panel controls"><label>Источник задач<select aria-label="Источник задач" disabled={running} value={state?.source??'demo'} onChange={e=>act('source',{source:e.target.value})}><option value="demo">Учебные данные</option><option value="live">Мой Яндекс Трекер</option></select></label><span className={'badge '+(state?.connection.connected?'good':'')}>{state?.connection.connected?'MCP подключён':'MCP подключится при запуске'}</span><button disabled={running} onClick={()=>act('run')}>{running?'Цепочка выполняется…':'Запустить цепочку →'}</button></section>
 {(error||run?.error)&&<p className="error" role="alert">{error||run?.error}</p>}<div className="pipeline">{steps.map((step,i)=><section className={'panel pipeline-step '+step.status} key={step.name}><span className="step-number">0{i+1}</span><span className={'badge '+(step.status==='completed'?'good':'')}>{statuses[step.status]}</span><h2>{names[step.name]}</h2><code>{step.name}</code><p>{['Снимок моих незавершённых задач','Категории сроков и точные показатели','Markdown + JSON вне репозитория'][i]}</p>{step.durationMs!==undefined&&<small>{step.durationMs} мс</small>}<details><summary>Вход и результат шага</summary><pre>{JSON.stringify({input:step.input??null,output:step.output??null},null,2)}</pre></details></section>)}</div>
 <div className="metrics">{[['Всего задач',run?.result?.metrics.total],['Просрочено',run?.result?.metrics.overdue],['Срок сегодня',run?.result?.metrics.today],['Без дедлайна',run?.result?.metrics.noDeadline]].map(([label,value],i)=><section className={'metric metric-'+i} key={label}><span>{label}</span><strong>{value??'—'}</strong></section>)}</div>
 <section className="panel"><div className="section-title"><h2>Сохранённый отчёт</h2>{run?.report&&<button className="secondary" onClick={showReport}>Показать Markdown</button>}</div>{run?.report?<><p className="answer">Отчёт сохранён. Каждый показатель рассчитан по снимку первого шага.</p><p className="file-path">{state?.dataDirectory}<br/>{run.report.markdownFile}<br/>{run.report.jsonFile}</p></>:<p className="empty">После успешного третьего шага здесь появится результат.</p>}{preview&&<pre className="report-preview">{preview}</pre>}</section>
 <div className="columns lower"><section className="panel"><h2>Передача данных</h2><p className="answer">Первый инструмент возвращает идентификатор снимка. Второй читает именно этот снимок и возвращает идентификатор сводки. Третий сохраняет именно эту сводку.</p><p className="muted">При ошибке цепочка останавливается. Повторное сохранение одной сводки использует те же имена файлов.</p></section><section className="panel"><h2>Каталог MCP</h2>{state?.connection.tools.map(tool=><p className="muted" key={tool.name}><strong>{tool.name}</strong><br/>{tool.description}</p>)}{!state?.connection.tools.length&&<button className="secondary" disabled={running} onClick={()=>act('connect')}>Получить список инструментов</button>}</section></div><footer>Порядок шагов задан программой. Для выполнения этой цепочки языковая модель не требуется.<br/>Названия, ключи и ссылки скрыты в результатах и новых отчётах; задачи в Трекере не изменяются.</footer></main></div>;
}
