import {useEffect,useState} from 'react';
type Tool={name:string;description:string;inputSchema:unknown};
type Server={id:string;title:string;connected:boolean;info:{name:string}|null;tools:Tool[]};
type Run={status:string;mode:string;answer:string;error:string|null;steps:{server:string;name:string;status:string;input:unknown;output:unknown;durationMs?:number}[];modelData:{tool:string;values:Record<string,number>}[];result:{date:string;metrics:Record<string,number>;issues:{label:string;dueDate:string|null}[]}|null;comparison:{available:boolean;deltas:Record<string,number>|null}|null;report:{reportId:string;markdownFile:string}|null};
type State={source:string;busy:boolean;servers:Server[];last:Run|null;requests:Record<string,string>;hasOpenAI:boolean;dataDirectory:string;budget:{requests:number;estimatedUsd:number;reservedUsd:number;limitUsd:number}};
const requestLabels:Record<string,string>={report:"Собрать, сравнить и сохранить отчёт",today:"Задачи на сегодня",overdue:"Просроченные задачи",last:"Последний сохранённый отчёт"};
export function App(){
 const[state,setState]=useState<State|null>(null),[request,setRequest]=useState('report'),[mode,setMode]=useState('demo'),[busy,setBusy]=useState(false),[error,setError]=useState(''),[preview,setPreview]=useState('');
 async function refresh(){const r=await fetch('/api/state');if(!r.ok)throw new Error('Сайт недоступен.');setState(await r.json());}
 useEffect(()=>{refresh().catch(e=>setError(e.message));const timer=setInterval(()=>refresh().catch(()=>{}),1000);return()=>clearInterval(timer);},[]);
 async function act(path:string,body:unknown={}){setBusy(true);setError('');setPreview('');try{const r=await fetch('/api/'+path,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const data=await r.json();if(!r.ok)throw new Error(data.error);setState(data);}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 async function showReport(){try{const r=await fetch('/api/report/'+state?.last?.report?.reportId);const data=await r.json();if(!r.ok)throw new Error(data.error);setPreview(data.markdown);}catch(e){setError((e as Error).message);}}
 const running=busy||state?.busy,run=state?.last;
 return <div className="shell"><aside><a className="brand" href="/">Т<span>·</span>ЛАБ</a><div className="series">MCP / ЯНДЕКС ТРЕКЕР</div><nav>{[16,17,18,19,20].map((day,i)=><div className={day===20?'nav-item active':'nav-item'} key={day}><span>{day}</span>{['Подключение','Первый инструмент','Расписание','Цепочка','Оркестрация'][i]}</div>)}</nav><div className="aside-note">Два MCP-сервера<br/>Единый агент</div></aside><main><header><span className="eyebrow">ДЕНЬ 20 / ОРКЕСТРАЦИЯ MCP</span><span className="local"><i/> Локальное приложение</span></header><section className="hero"><div><h1>Два сервера.<br/>Одна задача.</h1><p>Агент выбирает инструменты получения и анализа задач. Проследите маршрут от запроса до отчёта.</p></div><div className="hero-number">20<span>/20</span></div></section>
 <section className="panel controls"><label>Источник задач<select aria-label="Источник задач" disabled={running} value={state?.source??'demo'} onChange={e=>act('source',{source:e.target.value})}><option value="demo">Учебные данные</option><option value="live">Мой Яндекс Трекер</option></select></label><p className="muted">Два отдельных процесса · один набор задач</p><button className="secondary" disabled={running} onClick={()=>act('connect')}>Подключить серверы</button></section>
 <div className="server-grid">{(state?.servers??[]).map(server=><section className={'panel server-card '+server.id} key={server.id}><span className={'badge '+(server.connected?'good':'')}>{server.connected?'Подключён':'Ожидает'}</span><h2>{server.title}</h2><code>{server.info?.name??`tracker-${server.id}`}</code><p>{server.id==='data'?'Чтение назначенных мне задач из API Трекера.':'Расчёт сроков, сравнение и локальные отчёты.'}</p><details><summary>{server.tools.length} инструментов · каталог</summary>{server.tools.map(tool=><div className="tool-description" key={tool.name}><strong>{tool.name}</strong><p>{tool.description}</p><pre>{JSON.stringify(tool.inputSchema,null,2)}</pre></div>)}</details></section>)}</div>
 <section className="panel request-panel"><label>Запрос агенту<select aria-label="Запрос агенту" disabled={running} value={request} onChange={e=>setRequest(e.target.value)}>{Object.entries(state?.requests??{report:'Собрать, сравнить и сохранить сводку'}).map(([key,value])=><option key={key} value={key}>{requestLabels[key]??value}</option>)}</select></label><label>Исполнение<select aria-label="Исполнение" disabled={running} value={mode} onChange={e=>setMode(e.target.value)}><option value="demo">Демонстрация без модели</option><option value="live">Настоящий агент · OpenAI</option></select></label><button disabled={running||(mode==='live'&&!state?.hasOpenAI)} onClick={()=>act('run',{request,mode})}>{running?'Агент работает…':'Выполнить запрос →'}</button><p className="wide request-text">{state?.requests[request]}</p><p className="wide muted">В реальном режиме модель выбирает инструменты; приложение проверяет порядок и подставляет локальные идентификаторы. В демонстрации последовательность выбирает код.</p></section>
 {(error||run?.error)&&<p className="error" role="alert">{error||run?.error}</p>}<div className="metrics">{[['Всего задач',run?.result?.metrics.total],['Просрочено',run?.result?.metrics.overdue],['Срок сегодня',run?.result?.metrics.today],['Без дедлайна',run?.result?.metrics.noDeadline]].map(([label,value],i)=><section className={'metric metric-'+i} key={label}><span>{label}</span><strong>{value??'—'}</strong></section>)}</div>
 <div className="columns"><section className="panel"><div className="section-title"><h2>Маршрут выполнения</h2><span className="badge">{run?.status==='completed'?'Завершено':run?.status==='failed'?'Ошибка':running?'В работе':'Ожидает запроса'}</span></div><ol className="timeline routing">{run?.steps.map((step,i)=><li key={i}><span className={'route-server '+step.server}>{step.server==='data'?'Задачи Трекера':'Аналитика Трекера'}</span><h3>{step.name}</h3><p>{step.status==='completed'?'Выполнено':step.status==='running'?'Выполняется':step.status==='rejected'?'Порядок отклонён':'Ошибка'}{step.durationMs!==undefined?` · ${step.durationMs} мс`:''}</p><details><summary>Локальные параметры и результат</summary><pre>{JSON.stringify({input:step.input,output:step.output},null,2)}</pre></details></li>)}</ol>{!run?.steps.length&&<p className="empty">Здесь появится каждый вызов с указанием сервера.</p>}</section>
 <section className="panel"><h2>{run?.mode==='live'?'Ответ агента':'Результат выполнения'}</h2><p className="answer">{run?.answer??'Выберите запрос, чтобы увидеть результат.'}</p>{run?.comparison&&<div className="comparison"><h3>Сравнение с предыдущим отчётом</h3>{run.comparison.available?<p>Изменение просроченных: {run.comparison.deltas?.overdue??0}<br/>Изменение задач на сегодня: {run.comparison.deltas?.today??0}</p>:<p>Предыдущего отчёта нет. Этот запуск станет первой точкой сравнения.</p>}</div>}{run?.report&&<><p className="file-path">{state?.dataDirectory}<br/>{run.report.markdownFile}</p><button className="secondary" onClick={showReport}>Показать сохранённый отчёт</button></>}<details><summary>Только эти результаты доступны модели</summary><pre>{JSON.stringify(run?.modelData??[],null,2)}</pre></details><p className="muted">Запросов OpenAI: {state?.budget.requests??0} · оценка расхода: ${(state?.budget.estimatedUsd ?? 0).toFixed(5)}<br/>Локальный лимит: ${(state?.budget.limitUsd ?? 1).toFixed(2)} · резерв запросов без подтверждённого расхода: ${(state?.budget.reservedUsd ?? 0).toFixed(2)}</p></section></div>
 {preview&&<section className="panel lower"><h2>Сохранённый Markdown</h2><pre className="report-preview">{preview}</pre></section>}{run?.result&&<section className="panel lower"><h2>Обезличенные задачи · {run.result.date}</h2><p className="muted">Названия, ключи и ссылки скрыты. Номера относятся только к этой выборке.</p><div className="table-wrap"><table><thead><tr><th>Задача</th><th>Дедлайн</th></tr></thead><tbody>{run.result.issues.map(issue=><tr key={issue.label}><td><strong>{issue.label}</strong></td><td>{issue.dueDate??'Не задан'}</td></tr>)}</tbody></table></div>{!run.result.issues.length&&<p className="empty">Для выбранного периода задач нет.</p>}</section>}
 <footer>Разделение двух серверов учебное. Оба работают с задачами Трекера; аналитический сервер читает локальные снимки.<br/>Модель получает только числа и технические результаты. Названия, ключи и ссылки задач скрыты во всех результатах.</footer></main></div>;
}
